<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="DataFlowDiagramModel" nsURI="http://www.example.org/DataFlowDiagramModel"
    nsPrefix="DataFlowDiagramModel">
  <eClassifiers xsi:type="ecore:EClass" name="DataFlowDiagram">
    <eStructuralFeatures xsi:type="ecore:EReference" name="flow" upperBound="-1" eType="#//Flow"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Flow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceNode" lowerBound="1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destinationNode" lowerBound="1"
        eType="#//Node"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="destinationPin" eType="ecore:EClass ../../BehaviourModel/model/behaviourModel.ecore#//Pin"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePin" eType="ecore:EClass ../../BehaviourModel/model/behaviourModel.ecore#//Pin"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Node">
    <eStructuralFeatures xsi:type="ecore:EReference" name="behaviour" eType="ecore:EClass ../../BehaviourModel/model/behaviourModel.ecore#//Behaviour"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" eType="ecore:EClass ../../BehaviourModel/model/behaviourModel.ecore#//Label"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="External" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Store" eSuperTypes="#//Node"/>
  <eClassifiers xsi:type="ecore:EClass" name="Process" eSuperTypes="#//Node"/>
</ecore:EPackage>
